// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rdglm_index_loop
void rdglm_index_loop(const IntegerVector& group, List& subset);
RcppExport SEXP mbest_rdglm_index_loop(SEXP groupSEXP, SEXP subsetSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< List& >::type subset(subsetSEXP);
    rdglm_index_loop(group, subset);
    return R_NilValue;
END_RCPP
}
