# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdglm_index_loop <- function(group, subset) {
    invisible(.Call('mbest_rdglm_index_loop', PACKAGE = 'mbest', group, subset))
}

